// Copyright Recursoft LLC 2019-2021. All Rights Reserved.

#include "SMGraphK2.h"
#include "Nodes/RootNodes/SMGraphK2Node_RootNode.h"
#include "Utilities/SMBlueprintEditorUtils.h"
#include "Construction/SMEditorConstructionManager.h"


USMGraphK2::USMGraphK2(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
}

bool USMGraphK2::HasAnyLogicConnections() const
{
	if (bHasLogicConnectionsCached.IsSet())
	{
		return bHasLogicConnectionsCached.GetValue();
	}
	
	TArray<USMGraphK2Node_RootNode*> RootNodeList;

	// We want to find the node even if it's buried in a nested graph.
	FSMBlueprintEditorUtils::GetAllNodesOfClassNested<USMGraphK2Node_RootNode>(this, RootNodeList);

	for (USMGraphK2Node_RootNode* RootNode : RootNodeList)
	{
		if (RootNode->GetOutputNode())
		{
			const_cast<USMGraphK2*>(this)->bHasLogicConnectionsCached = true;
			return true;
		}
	}

	const_cast<USMGraphK2*>(this)->bHasLogicConnectionsCached = false;
	return false;
}

void USMGraphK2::ResetCachedValues()
{
	bHasLogicConnectionsCached.Reset();
}

void USMGraphK2::PostRename(UObject* OldOuter, const FName OldName)
{
	Super::PostRename(OldOuter, OldName);

	const ESMEditorConstructionScriptProjectSetting ConstructionProjectSetting = FSMBlueprintEditorUtils::GetProjectEditorSettings()->EditorNodeConstructionScriptSetting;
	if (ConstructionProjectSetting == ESMEditorConstructionScriptProjectSetting::SM_Standard)
	{
		// Find correct blueprint to run cs for.
		USMBlueprint* Blueprint = FSMBlueprintEditorUtils::FindBlueprintFromObject(this);
		if (!Blueprint)
		{
			// If this graph is being deleted the new outer would be the transient package, try to find old package.
			Blueprint = FSMBlueprintEditorUtils::FindBlueprintFromObject(OldOuter);
		}
		if (Blueprint)
		{
			FSMEditorConstructionManager::GetInstance()->RunAllConstructionScriptsForBlueprint(Blueprint);
		}
	}
}

void USMGraphK2::NotifyGraphChanged()
{
	Super::NotifyGraphChanged();
	
	if (UBlueprint* Blueprint = FSMBlueprintEditorUtils::FindBlueprintForGraph(this))
	{
		if (!Blueprint->bBeingCompiled && !Blueprint->HasAnyFlags(RF_NeedLoad | RF_NeedPostLoad))
		{
			FSMBlueprintEditorUtils::FixUpAutoGeneratedFunctions(Blueprint, true);
		}
	}
}

void USMGraphK2::NotifyGraphChanged(const FEdGraphEditAction& Action)
{
	Super::NotifyGraphChanged(Action);
}
